const data_cand = [{"ballot_number":1,"first_name":"Arnoldo","last_name":"Kordovani","picture":"https://robohash.org/quiavoluptatem.png?size=100x100&set=set1","party":5},
{"ballot_number":2,"first_name":"Leyla","last_name":"Garms","picture":"https://robohash.org/corruptialiasofficiis.png?size=100x100&set=set1","party":1},
{"ballot_number":3,"first_name":"Cameron","last_name":"Howieson","picture":"https://robohash.org/omnisprovidentodit.png?size=100x100&set=set1","party":3},
{"ballot_number":4,"first_name":"Nelli","last_name":"Craghead","picture":"https://robohash.org/pariaturquasiconsequuntur.png?size=100x100&set=set1","party":2},
{"ballot_number":5,"first_name":"Charlean","last_name":"Bellard","picture":"https://robohash.org/officiaquiomnis.png?size=100x100&set=set1","party":4},
{"ballot_number":6,"first_name":"Adrien","last_name":"Chataignier","picture":"https://robohash.org/fugiatutsit.png?size=100x100&set=set1","party":5},
{"ballot_number":7,"first_name":"Celestyn","last_name":"England","picture":"https://robohash.org/perspiciatisasperioresquisquam.png?size=100x100&set=set1","party":4},
{"ballot_number":8,"first_name":"Zuzana","last_name":"Ormonde","picture":"https://robohash.org/quiasequiconsectetur.png?size=100x100&set=set1","party":3},
{"ballot_number":9,"first_name":"Ahmad","last_name":"Stoffler","picture":"https://robohash.org/velestiure.png?size=100x100&set=set1","party":1},
{"ballot_number":10,"first_name":"Hedda","last_name":"Hannond","picture":"https://robohash.org/doloresrerumiusto.png?size=100x100&set=set1","party":2},
{"ballot_number":11,"first_name":"Tris","last_name":"Daintree","picture":"https://robohash.org/minusetatque.png?size=100x100&set=set1","party":1},
{"ballot_number":12,"first_name":"Hort","last_name":"Wrey","picture":"https://robohash.org/quomagnioccaecati.png?size=100x100&set=set1","party":4},
{"ballot_number":13,"first_name":"Jaime","last_name":"Took","picture":"https://robohash.org/utautemvoluptas.png?size=100x100&set=set1","party":3},
{"ballot_number":14,"first_name":"Forester","last_name":"Lowton","picture":"https://robohash.org/nonmaioresin.png?size=100x100&set=set1","party":2},
{"ballot_number":15,"first_name":"Bern","last_name":"Robichon","picture":"https://robohash.org/autemutquo.png?size=100x100&set=set1","party":3},
{"ballot_number":16,"first_name":"Maryanna","last_name":"Risson","picture":"https://robohash.org/sinteaesse.png?size=100x100&set=set1","party":2},
{"ballot_number":17,"first_name":"Forest","last_name":"Harding","picture":"https://robohash.org/molestiaenullaab.png?size=100x100&set=set1","party":4},
{"ballot_number":18,"first_name":"Clevey","last_name":"Saladine","picture":"https://robohash.org/autemfugitcum.png?size=100x100&set=set1","party":3},
{"ballot_number":19,"first_name":"Abbott","last_name":"Di Matteo","picture":"https://robohash.org/rerumvoluptatemnumquam.png?size=100x100&set=set1","party":1},
{"ballot_number":20,"first_name":"Buffy","last_name":"Maultby","picture":"https://robohash.org/similiquequibusdamdolorum.png?size=100x100&set=set1","party":2}]

export default data_cand;